### ISSUE TITLE
TransactionDetail. Implement view merkle data in explorer.

### ISSUE THREAD

**Issue by AnthonyLaw** [nemgrouplimited/symbol-explorer#324]

**Comment by AnthonyLaw** [comment]
R&D for UI view for Merkle data.

**Comment by AnthonyLaw** [comment]
Under Block Detail able to view Merkle root info.

![image](https://user-images.githubusercontent.com/5649156/89270486-fba69880-d66d-11ea-86b8-aa33ce951e02.png)

Under Transaction Detail able to view Merkle Path info

![image](https://user-images.githubusercontent.com/5649156/89270593-21cc3880-d66e-11ea-9e16-864ca05fd3ee.png)

**Comment by jabo38** [comment]
I haven't seen very many Merkle Trees or paths in an explorer before, but that is also because most other chains don't have receipts. 

So this is a really nice way to show how we have something others don't which makes Symbol a little more shiny.

**Comment by AnthonyLaw** [comment]
@jabo38 agree, for now this just a start, will thinking how to build the `tree` from all the `transaction hash`, not sure it's possible and have to discuss with @evias .

After that @OlegMakarenko can design MerkleGraphic for that :)
