### ISSUE TITLE
AccountDetail. Most addresses in the Nodes section are not known the the network. Details in explorer are a bit confusing. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-explorer#418]
![image](https://user-images.githubusercontent.com/10395907/80543651-fe119c00-8974-11ea-8e08-62b18cfdf1dd.png)

When I click through to these addresses, like for instance the first one is TBB6OA3DF2WLDKHWOLTQEZOOLZ2CGCDZLKDPRNV3, and I go to find out more about the address, I'm taken to a screen that has a whole lot of nothing. 

http://explorer.symboldev.network/account/TBB6OA3DF2WLDKHWOLTQEZOOLZ2CGCDZLKDPRNV3

And I get it from a developer perspective... the account is not known to the network. Except that this is kind of confusing to the user because logically, if I see it in the Explorer, then the explorer knows about it somehow, but when I click through it says it is unknown. So there is an inconsistency there because how can the explorer know enough about the account to display it on the page before and give me a click-through, but then say it doesn't know it. 

Also, there are 10 different boxes that each basically says "Nothing to show". 

So I'm thinking if an account is not known to the network, then maybe it is better to only show one box, the top one. And then we say something a little different. So, instead of saying "account is not known to the network" but instead say something like "This account does not have a public key yet" and just leave it with that one box and only one box. Hopefully, then the community can infer that not having a known public key means we can show any other information.

**Comment by AnthonyLaw** [comment]
![image](https://user-images.githubusercontent.com/5649156/80691085-5033f800-8b02-11ea-9756-02ec2cb296b4.png)

it may look like, what you think?

we can easily to hide the `Box or Card`, if the dataset is empty by changing config.

it will apply for all address, example some address doesn't have `Importance History`, it will hide the Card as well.

**Comment by OlegMakarenko** [comment]
Yes it is because the server returns 404 `{"code":"ResourceNotFound","message":"no resource exists with id 'TBB6OA3DF2WLDKHWOLTQEZOOLZ2CGCDZLKDPRNV3'"}` for the address detail. But in the Node list all these adresses are present.

>  we can easily to hide the Box or Card, if the dataset is empty by changing config.

As I remember we don't hide an empty Cards so users can understand that this dataset is present in the `Account` type, but is empty for the current account. The solution can be to hide cards only when the error occurred in the Page level (in this case - Account Detail fetch failed)
