### ISSUE TITLE
Statistics Chart. Animation Effect doesn't work properly

### ISSUE THREAD

**Issue by AnthonyLaw** [nemgrouplimited/symbol-explorer#539]
Browser: Mozilla FireFox

![explorer](https://user-images.githubusercontent.com/5649156/87657203-167f9e80-c78d-11ea-9532-f8f37bc358b4.gif)

I believe if able to turn off those effect may solve the problem.

**Comment by OlegMakarenko** [comment]
This happens because of the large amount of data

**Comment by AnthonyLaw** [comment]
Merged into `Main`
