### ISSUE TITLE
Double slash causes blank page

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-explorer#542]
Related issue:
https://github.com/nemfoundation/symbol-desktop-wallet/issues/459

When I have a double slash in the link it causes explorer to present only blank page. Example URL:

http://explorer-96x.symboldev.network//account/TAUTUPN57JYRZGVQ26IMX4RJ7EXU4CMLZWNGKEA

**Comment by AnthonyLaw** [comment]
After did some research, the double slash after the domian issue it not really related to explorer itself,
The explorer route already handle those unrelated route to 404.

Example the double slash after route
http://explorer-96x.symboldev.network/account//TAUTUPN57JYRZGVQ26IMX4RJ7EXU4CMLZWNGKEA

I will disucss with the deployment team and solve this issue on `htaccess`

**Comment by AnthonyLaw** [comment]
I will close this, the issue already fixes in nemgrouplimited/symbol-desktop-wallet#459

reopen it, if needed.
