### ISSUE TITLE
Improve UI of HashLock TransactionGraphic

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-explorer#620]
![image](https://user-images.githubusercontent.com/33131259/93605916-0b84fc80-f9d0-11ea-81cf-447782908314.png)
![image](https://user-images.githubusercontent.com/33131259/93606274-80583680-f9d0-11ea-94a1-b81cf252c261.png)

Move `transactionType` under the **arrow**. `Duration` can be placed in the **popup** or under **LockIcon**

**Comment by jabo38** [comment]
looks okay to me
