### ISSUE TITLE
Terms & Privacy

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-explorer#629]
- [x] Review **Terms** copy | http://explorer.testnet.symboldev.network/terms
- [x] Review **Privacy Policy** copy | http://explorer.testnet.symboldev.network/privacy

**Note**: Rename `NEM.io Foundation` to `NSL` in Explorer footer.

**Comment by JackNEM** [comment]
Is this going to be the same as issue #531 for symbol desktop wallet, content-wise?

**Comment by JackNEM** [comment]
I will follow up with Steve about content for T&Cs

**Comment by AnthonyLaw** [comment]
>Note: Rename NEM.io Foundation to NSL in Explorer footer.

Resolved into main.

**Comment by OlegMakarenko** [comment]
Privacy Policy is updated
