### ISSUE TITLE
Account Detail Page doesn't work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-explorer#638]
Sometimes not all data is displayed on a Account Detail Page.
```
{"code":"TooManyRequests","message":"You have exceeded your request rate of 20 r/s."}
```
![image](https://user-images.githubusercontent.com/33131259/94438827-4cd39400-01a8-11eb-9d32-0d0e6f022f93.png)
![image](https://user-images.githubusercontent.com/33131259/94438893-5e1ca080-01a8-11eb-912d-3f474daddae7.png)

**Comment by AnthonyLaw** [comment]
@OlegMakarenko can you update the network to `0.10.0.x` ?
it should have a higher rate.

**Comment by OlegMakarenko** [comment]
Still the issue
Node: http://api-01.eu-central-1.0.10.0.x.symboldev.network:3000/
http://explorer-0.10.0.x-01.symboldev.network/accounts

**Comment by AnthonyLaw** [comment]
As the Issue often happens, I believe is caused by `isLastPage` checking on pagination.
Because every API request from Card is x 2. 

Propose a solution.
- Remove extra isLastPage Checking.

@OlegMakarenko what you think?
