### ISSUE TITLE
Rich list showing empty

### ISSUE THREAD

**Issue by Vektrat** [nemgrouplimited/symbol-explorer#644]
Not sure if this worked before, just noticed it, if it's supposed to work with XYM then the filtered ID is wrong ^^

Also note that you can customize the currency (not necessarily XYM), as a suggestion for an extra feature if not in the roadmap

**Comment by AnthonyLaw** [comment]
@Vektrat Good catch, thanks mate :)

> Also note that you can customize the currency (not necessarily XYM), as a suggestion for an extra feature if not in the roadmap

Yeah, it can build `Advance Search` to fully utilize filter enpoint.
