### ISSUE TITLE
Problem with presenting address without outgoing transactions.

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-explorer#663]
Explorer: explorer-0.10.0.x-01.symboldev.network

Account TDXXMQM7SZ6CGILWVH2KA4MC5DUVH7D7LGK7HXA has one incoming transaction from faucet.

When I'm opening http://explorer-0.10.0.x-01.symboldev.network/accounts/TDXXMQM7SZ6CGILWVH2KA4MC5DUVH7D7LGK7HXA in explorer sometimes I can see:

![image](https://user-images.githubusercontent.com/17684281/95027124-7869e900-0696-11eb-88e7-ca8f61de6d59.png)

and sometimes:

![image](https://user-images.githubusercontent.com/17684281/95027130-84ee4180-0696-11eb-9f2c-3b26b31f3b16.png)

Both are invalid:
- first one is invalid because address without outgoing transactions (public key not known) but with incoming transactions should be presented in explorer
- second one is invalid because public key is not known and 0000000000000000000000000000000000000000000000000000000000000000 shouldn't be presented.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever thank you. Definitely there should be "unknown" value instead of "000..."

**Comment by cryptoBeliever** [comment]
@AnthonyLaw  according to information from Wayon if publicKeyHeight = 0 then the publickey value is unknown.

**Comment by AnthonyLaw** [comment]
@cryptoBeliever Alright, Thanks mate!
