### ISSUE TITLE
Transaction Detail page doesn't work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-explorer#672]
```
{"code":"TooManyRequests","message":"You have exceeded your request rate of 20 r/s."}
```
http://localhost:8080/transactions/22E5BB5756FE9EF4C88C31B82B2FC1FA97D21E65E33A5C823513FACAB86F7D8E

**Comment by AnthonyLaw** [comment]
Didn't see this issue on 10.0.x network, I believe REST node already increases the request rate.
Reopen it, if have the same issue again.
