### ISSUE TITLE
Deployment. We need explorer docker image support environment variables

### ISSUE THREAD

**Issue by AnthonyLaw** [nemgrouplimited/symbol-explorer#683]
Problems:
- Explorer is not flexible to change node Url in docker images, because it just a static web application after the build.
- We are not able to pass environment variables to config static web applications.

Even though vueJS support [environment-variables](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables), but env variables are only able to read before the build.

The goal:
- create the one-off build and dynamic config node URL.

**Comment by AnthonyLaw** [comment]
IMO we may need change to Nuxtjs because it supports SSR.

@OlegMakarenko what do you think about it?

**Comment by JackNEM** [comment]
Let's discuss this in a client team meeting.

**Comment by fboucquez** [comment]
What about binding a folder with a custom setup.json file and re-run the "npm build" when booting the image? 

The external config file could be loaded with an env param here:

https://github.com/nemgrouplimited/symbol-explorer/blob/main/vue.config.js#L9 

Then the user would need to run a new build when botting the container with a "run" docker param.

**Comment by AnthonyLaw** [comment]
>What I would do is move setup.json from vue.config.js and put it next to the index.html. Either an extended index.html or JS via ajax could load the setup.json object at runtime from http://localhost/setup.json (or relative ./setup.json) path. The setup.json object won't be merged in the bundle files, it will be loaded from an external json file.

it sounds good to me, I think this is a good idea.

>So we create the image as we do, the new "docker run" command will swap the /usr/share/nginx/html/setup.json with another custom one. The app will load the new one at runtime when the users open the app.

agree with that.

thanks for the suggestion 👍

**Comment by fboucquez** [comment]
I got a working branch where the config/setup json is loaded with a js file. Not ideally but it solves the ordering problem issue.

**Comment by OlegMakarenko** [comment]
@fboucquez also as an idea - if we need to use ENV variables, we can create a simple one-file node.js server which will return this vars to explorer client on it's start

**Comment by fboucquez** [comment]
Thanks, @OlegMakarenko . I was thinking about starting a node server instead of ngnix so it can be a bit smarter. But nginx is working fine I didn't want to change too much what's there. We may need ENV variables in the future, swapping a file may not be possible when working with ECS. This issue would be common for other services like rest. Let's handle that one there.
