### ISSUE TITLE
Replace hardcoded XYM text from i18n properties

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-explorer#684]
I'm not 100 where they are displayed, but there are XYM text i18n files and some js files.
The XYM text should be replaced with the network currency short name (for example, `my.coin` should show `coin`).

We want to service the explorer in private networks where the main and harvest currencies won't be XYM. I'm including the explorer into bootstrap so you can test how it could look when running on private networks.

Examples:

https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/config/i18n/en-us.json#L147
https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/TransactionSchema.vue#L286

https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/TransactionSchema.vue#L243
What are these values? Where are they coming from?

https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/transaction-graphic/TransferTransactionSchema%20copy.vue
Is this file correct? Should it be removed?

**Comment by OlegMakarenko** [comment]
@fboucquez thank you. Yes [TransactionSchema](https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/TransactionSchema.vue#L286) and [TransferTransactionSchema](https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/components/transaction-graphic/TransferTransactionSchema%20copy.vue) should be removed
