### ISSUE TITLE
Address are not displayed correctly

### ISSUE THREAD

**Issue by xembook** [nemgrouplimited/symbol-explorer#701]
in the view of Transaction Graphic, address are not displayed correctly
and recipient URL is not correctly 
for example ,
`http://explorer-0.10.0.x-01.symboldev.network/accounts/[object%20Object]`

<img width="425" alt="スクリーンショット 2020-10-24 2 00 57" src="https://user-images.githubusercontent.com/53205023/97032586-07cf3180-159d-11eb-9439-cbf100129b03.png">

could you please check this , thank you.

**Comment by AnthonyLaw** [comment]
Thanks for reporting this.
I had tested my machine, it seems all good.

may I know in which transaction hash?

**Comment by xembook** [comment]
for example ,
http://explorer-0.10.0.x-01.symboldev.network/transactions/5342367022F06F7F3CF18B21F5F009BB1DBC5295101B34B2DE67D3F6C90A5B70

**Comment by OlegMakarenko** [comment]
@AnthonyLaw seems like a new version is not deployed

**Comment by OlegMakarenko** [comment]
#615 #619

**Comment by AnthonyLaw** [comment]
Yeah, wait for deploy, and will update here :)

**Comment by AnthonyLaw** [comment]
@xembook @OlegMakarenko 

Latest explorer deployed :) 

I tested all good now, I will close this issue now, reopen it if needed.
