### ISSUE TITLE
Transaction Detail. Doesn't display info for some transactions

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-explorer#703]
/transactions/869CBF6C1BEC26BB924222EADE09137D2393CB3595E32E78EA99A02C12FB59F2

![image](https://user-images.githubusercontent.com/33131259/97203294-47746400-17bd-11eb-9a12-dbfb8e21fc51.png)

**Comment by AnthonyLaw** [comment]
Error report here.

https://github.com/nemtech/catapult-rest/issues/496

but in explorer, we can do something to avoid this error.

**Comment by AnthonyLaw** [comment]
We will handle the error on the Client-side, as long as we are able to retrieve Transaction info, that's not possible confirmation is fail.
