### ISSUE TITLE
Display all transactions at one page for an account

### ISSUE THREAD

**Issue by ivyfung1** [nemgrouplimited/symbol-explorer#704]
Now, when I check on an account, I can see all the transactions of the account, the fund transferred, received and the transaction fees incurred. However, I can't see the rental fee of namespaces and mosaics. 
To check on the rental fee, I will need to click on the namespace/mosaic, and then click on the block height to link me to the block info and find out about the rental fee incurred. 

It would be good to have all the transaction that involved changing the balance of the account listed in one page, like a bank statement.

**Comment by AnthonyLaw** [comment]
Well, In that case, I will add the Receipt's TransactionStatement data on the Account Detail page.
