### ISSUE TITLE
some headers don't look nice when cut off. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-explorer#741]
In the following example, it would be better if the block height header was like the following:

Block
Height

instead of

Block Heigh
t
---
also it would be nice if confirmation was like the following

Confirm-
ation

instead of 

Confirmatio
n
----

In different examples throughout the app, this happens on mobile. The explorer experience is quite good on mobile, but this could be improved to make it more impressive. 

![IMG_4603](https://user-images.githubusercontent.com/10395907/102278177-f47e7980-3eee-11eb-8dd0-0d8ce3d4781d.PNG)

**Comment by OlegMakarenko** [comment]
fixed
