### ISSUE TITLE
NEM Foundation is still mentioned in Explorer

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#748]
Since the NEM Foundation no longer exists, the footer+Terms&Privacy in Explorer should be updated.

![foundation](https://user-images.githubusercontent.com/46584115/103556926-c5867280-4eb2-11eb-9833-0890972d0349.png)

See also:
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/766

, thx for that.

https://github.com/nemgrouplimited/symbol-explorer/search?q=foundation

**Comment by AnthonyLaw** [comment]
Thanks 👍🏼 
Yeah, I was waiting for feedback #629 from the team and fix it together.

but let me do it separately.
