### ISSUE TITLE
different display of "account details" of an address in the same browser

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#751]
http://explorer-0.10.0.x-01.symboldev.network/accounts/TCXNSGLNKAZLQMO3KL2ZQXDK4HG3CH642LWKJHA
browser:
- firefox_78.6.0esr(64-bit) linux
- chromium 87.0.4280.88 (64-bit) linux
![account-detail-1](https://user-images.githubusercontent.com/46584115/103999459-3375b700-519d-11eb-9570-cef81cb5c770.png)

-----

![account-detail-2](https://user-images.githubusercontent.com/46584115/103999488-3a042e80-519d-11eb-950f-ffe293ee4c92.png)

**Comment by AnthonyLaw** [comment]
it's missing the Account balance and owned mosaic section on firefox ?

**Comment by garm01** [comment]
Yes, firefox, chromium.
Since I can no longer reproduce this different display, I will close this issue for now. Thx!
