### ISSUE TITLE
" This account does not have a public key yet "

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#752]
Hi, I'm not sure if the problem is completely fixed (closed issues #663, #676).
Explorer keeps showing "This account does not have a public key yet", 
although the account has a public key.
Sometimes it works the first time the address is called. However, it is often necessary to reload the page more than once.

- firefox
- opera
- chromium

**Comment by AnthonyLaw** [comment]
Thanks for the report, will have a look at this.

**Comment by garm01** [comment]
Thank you! At the moment I can't reproduce this issue anymore, so I would close it for now.
