### ISSUE TITLE
Do not expose whole ENV in /config

### ISSUE THREAD

**Issue by gimer** [nemgrouplimited/symbol-explorer#754]
https://github.com/nemgrouplimited/symbol-explorer/blob/cbd11b9d52829ee93b9b83930d0c7b17254829bc/server.js#L14

Hello,

I would argue, that exposing whole env with all `npm_` variables and with all ENV vars like `HOME`, `PATH`, `NODE_VERSION` probably is not the greatest idea (or at least it shouldn't be publicly accessible)

**Comment by AnthonyLaw** [comment]
Agree, it should only expose variables used inside the application.
Thanks
