### ISSUE TITLE
Please add two column bar graphs of node heights (and finalized heights)

### ISSUE THREAD

**Issue by Jaguar0625** [nemgrouplimited/symbol-explorer#755]
```
Height | Bar (Count)
100 |****** 9 |
101 |*********** 15 |
102 | 3 |
```

**Comment by Jaguar0625** [comment]
consider also allowing sorting of nodes table (assuming height and finalized height columns are added)

**Comment by AnthonyLaw** [comment]
merged in main

**Comment by OlegMakarenko** [comment]
> consider also allowing sorting of nodes table (assuming height and finalized height columns are added)

Opened a separate issue for this:
https://github.com/nemgrouplimited/symbol-explorer/issues/797
