### ISSUE TITLE
Unable to check harvesting history

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-explorer#764]
In the current version of Explorer, I cannot check my harvesting history as below. 
This is very inconvenient.

![91E84382-65BB-4FB8-956B-C5E5D90208A3](https://user-images.githubusercontent.com/28587337/105021727-38374680-5a8c-11eb-8367-0b4a1362f6a7.jpeg)

In the previous version, I would be able to check the history as followings.

![B14DFB43-034D-4245-8181-8C6A12E4490B](https://user-images.githubusercontent.com/28587337/105021785-4c7b4380-5a8c-11eb-8073-1f639425705e.jpeg)

The prev. version looks good to me.

Is it possible to change it so that I can check the harvesting history like in the previous version, please?

Thanks!

**Comment by AnthonyLaw** [comment]
@ryo-opening-line thanks for the report on this issue.
We have patched the update a few days ago. it should be already resolved this issue.

can you check again?

**Comment by AnthonyLaw** [comment]
I will close this.
Reopen the issue, if needed.
