### ISSUE TITLE
The transaction display in 'Account View' is showing the deadline time, change it to the confirmed time.

### ISSUE THREAD

**Issue by GodTanu** [nemgrouplimited/symbol-explorer#765]
I'm viewing the Explorer in Japanese.
The correct time zone is selected when I use "transactions".

However, when I view it in "accounts", the time zone does not match.

transactions
![image](https://user-images.githubusercontent.com/20492223/105145257-d46f5500-5b41-11eb-92e8-55ff5efeee93.png)

accounts
![image](https://user-images.githubusercontent.com/20492223/105145342-f36de700-5b41-11eb-83f0-33b6ecee37e9.png)

**Comment by AnthonyLaw** [comment]
Thanks for the feedback, I will take a look :)

**Comment by AnthonyLaw** [comment]
Hi there, I'm not sure I understand your question correctly.

I checked on my machine. 

Dealine (期限) - 2021-01-20 18:56:48 - Dealine of Transaction
Date ( 日付) - 2021-01-20 16:56:58 - Data confirmed into the block 

it seems correct for me.

**Comment by GodTanu** [comment]
Oh, I was wrong about that, too. 
If it was deadlines, it was the correct indication. I apologize for that.
However, does it make sense to show this as a Dealine ? The transaction confirmed time should be displayed here.

**Comment by AnthonyLaw** [comment]
Yeah, the reason is that the transaction data itself is not coming with the confirmed time, it needs to get from the block information by the confirmed height.

but I agree with you. it should display a confirmed time.
I will see how can I improve it. 👍🏼

**Comment by GodTanu** [comment]
Changed the title. Please change it if it is inappropriate. Thank you very much.
