### ISSUE TITLE
Rich List -> More in Account page doesn't work

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-explorer#768]
Rich List -> More in Account page does not seem to work.

Here're the steps:

1. Show Accounts page
![image](https://user-images.githubusercontent.com/28587337/105256287-d2040e00-5bc8-11eb-9be4-6764d3257589.png)

2. Select Rich List
![image](https://user-images.githubusercontent.com/28587337/105256432-1b545d80-5bc9-11eb-9bf5-6a09ea9c2c5a.png)

3. Select More
![image](https://user-images.githubusercontent.com/28587337/105256515-3c1cb300-5bc9-11eb-98b1-a8d5edc9cab3.png)

4. Nothing to show
![image](https://user-images.githubusercontent.com/28587337/105256574-5787be00-5bc9-11eb-8c4b-5c68c0c7b17b.png)

Could you check it, please?

Thanks.

**Comment by AnthonyLaw** [comment]
Thanks.
I have checked on the REST side, it's returned an empty array. 
So it's valid in Explorer.

But it looks like a REST issue https://github.com/nemtech/catapult-rest/issues/558
I have reported.

**Comment by ryo-opening-line** [comment]
@AnthonyLaw  Hi Anthony. Thanks for checking!

**Comment by AnthonyLaw** [comment]
Another Issue releted.

https://github.com/nemtech/catapult-rest/issues/576

**Comment by AnthonyLaw** [comment]
Resolved in REST
