### ISSUE TITLE
getNativeNamespaces needs to filter by namespaces with infinite duration

### ISSUE THREAD

**Issue by Jaguar0625** [nemgrouplimited/symbol-explorer#769]
https://github.com/nemgrouplimited/symbol-explorer/blob/main/src/infrastructure/NamespaceService.js#L329

The real nemesis block will have a few "native" namespaces (symbol, xym) with an infinite duration.

But, it will have many more user namespaces (registered via optin) that will have a one year duration. These shouldn't be preloaded (and will have very negative performance implications if they are). Currently, a side effect is that all of these namespaces are displayed as INFINTE.

**Comment by AnthonyLaw** [comment]
Agree, I was thinking all native namespace is created in the Nemesis block, but never think of `registered via optin`.

I will change it to read the "native" namespace from the config file, as it already predefined in the nemesis block. :)

thanks for the feedback.
