### ISSUE TITLE
suggestion: Improved display of Blocks

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-explorer#774]
Please make it possible to see the latest blocks without having to reload them manually.

![ 2021-01-25 16-06-29-421](https://user-images.githubusercontent.com/59822825/105672247-6c48b680-5f27-11eb-9e56-2b1ad57d19be.png)
This is still old because I didn't reload it.

**Comment by AnthonyLaw** [comment]
Right now,  explorer should listen to every new block created.
it working on my machine.

Can you try again to reload the explorer, and wait into the block pages for around 1 min?
you should see the new block created from the list.

**Comment by OlegMakarenko** [comment]
If this was a bug, I cannot reproduce it now. New blocks appear without reloading the page
