### ISSUE TITLE
If namespaces consist of only one letter or number, they will not be displayed correctly.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#779]
If you click on the namespace ID, the namespace is displayed correctly.
http://explorer.testnet.symboldev.network/namespaces/DFD36A7FA45C478A

---

![namespace3](https://user-images.githubusercontent.com/46584115/107528512-37d92980-6bba-11eb-85d0-faa5d4c524fc.png)

----
----

If you click on the namespace name you get an error message.
http://explorer.testnet.symboldev.network/namespaces/2

---

![namespace2](https://user-images.githubusercontent.com/46584115/107528473-2b54d100-6bba-11eb-9300-29995e8fdf44.png)

**Comment by AnthonyLaw** [comment]
Thanks for report this. 👍🏼
