### ISSUE TITLE
Mark clearly expired mosaics

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-explorer#785]
This account owns an expired mosaic `365912C49D54FB71`:
http://explorer.testnet.symboldev.network/accounts/TACLIASRZC4QZLVAUM6CA5QB5ACY37SFTY7MGGI
But you have to click on the mosaic and see the details to find that it expired in block `110844` which is in the past.

Could this be indicated more clearly? The wallet simply hides these mosaics.

**Comment by AnthonyLaw** [comment]
Good catch!

I will apply the same how wallet display :)
