### ISSUE TITLE
No different separators under Reported Balance (Node Rewards Program Range display) 

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#802]
To avoid confusion, different separators should be used here as well. Just like in other areas of the explorer(or wallet). 
(Node Rewards Program ---> Chain ---> Node Balance ---> Reported Balance)

---

![Node_balance0](https://user-images.githubusercontent.com/46584115/109359764-4dbb3f80-7886-11eb-95df-54617a979705.png)

---

![Node_balance-2](https://user-images.githubusercontent.com/46584115/109360085-e356cf00-7886-11eb-98eb-beb849f605a2.png)
![Node_balance3](https://user-images.githubusercontent.com/46584115/109360106-ebaf0a00-7886-11eb-86e1-9c9539478829.png)

**Comment by OlegMakarenko** [comment]
Thank you. Fixed 
![image](https://user-images.githubusercontent.com/33131259/109621868-2beee080-7b44-11eb-813e-486b7e7b7f3a.png)
