### ISSUE TITLE
Detail display "Host Location" is not displayed correctly. The last character of the address is also missing.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#803]
![Detail](https://user-images.githubusercontent.com/46584115/109401968-63963680-7952-11eb-89d5-4c18383440d2.png)

---

Under "Nodes" it is displayed correctly.

![Details-2](https://user-images.githubusercontent.com/46584115/109402060-f040f480-7952-11eb-8ec2-0075a23e89a5.png)

**Comment by garm01** [comment]
TD5VJN2M5RHPWMQSZGH6SRAJQHAWPEZT6T5CM6I

![vistel3](https://user-images.githubusercontent.com/46584115/109402193-17e48c80-7954-11eb-82d9-942fd5660ccf.png)

**Comment by OlegMakarenko** [comment]
Thanks for reporting the issue. Fixed
