### ISSUE TITLE
In explorer, not all valid namespaces are displayed in the details view.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#804]
Under the detail view "Owned Namespaces" max. 10 namespaces are displayed, although the account has registered >10 valid namespaces.   TBQZVMBZEOU6YDL5N6HDREIPZLQ6JKRUZZUXP5Q

---

![namespace-reg-2](https://user-images.githubusercontent.com/46584115/109424143-b91a2400-79e2-11eb-9e4d-0de6d951809a.png)

---

![namespace-reg-3](https://user-images.githubusercontent.com/46584115/109424053-62ace580-79e2-11eb-83b6-6ea33c78fffc.png)

**Comment by AnthonyLaw** [comment]
Thanks for reporting. 👍🏼

**Comment by OlegMakarenko** [comment]
fixed
