### ISSUE TITLE
Harvesting fees not presented for pretty address in url

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-explorer#867]
Harvesting fees are presented only if we put address without dashes.

Example:
http://explorer.symbolblockchain.io/accounts/NDKYBCN3GMJ6TM6TLVWLUYVXIS7WTZ4A2QXJ5HI
http://explorer.symbolblockchain.io/accounts/NDKYBC-N3GMJ6-TM6TLV-WLUYVX-IS7WTZ-4A2QXJ-5HI

For the second one harvesting blocks section is not presented:

![image](https://user-images.githubusercontent.com/17684281/113620497-abe3fb00-965a-11eb-9a76-bc3b1dffb929.png)

**Comment by AnthonyLaw** [comment]
merged into Dev
