### ISSUE TITLE
block creation time is displayed incorrectly for a short time.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-explorer#873]
When a new block appears in the explorer, " 364 days ago " is often displayed for a (very)short time under "Created". 

---

![blockcreation](https://user-images.githubusercontent.com/46584115/114457124-f70f8800-9bdd-11eb-8193-9e774b6b889a.png)

**Comment by OlegMakarenko** [comment]
Merged into `dev`
