### ISSUE TITLE
Double popup when hovering over transaction message icon

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-explorer#912]
![20210607_085412](https://user-images.githubusercontent.com/10949043/120972809-6fbe3b00-c76e-11eb-83b6-33a88db2b535.jpg)

In an account's transaction list, when hovering over the little orange message icon, a white popup appears with the message content.
A few seconds later, though, a second popup appears, this time black and smaller, with a useless "Object object" message.

(Sorry about the screen picture, screencap does not work because pressing any key dismisses the popup)

Chrome on Windows.

**Comment by AnthonyLaw** [comment]
Hi @segfaultxavi  

it has fixed [here](https://github.com/nemgrouplimited/symbol-explorer/issues/885).

The latest fix has deployed on our Testnet explorer, you try over there :)

I will close the issue now, if found any issue will reopen it.
